Update for lock.go
mtfelian/lock pull request #2
Opened 2016-12-05 00:23 UTC by diaevd

Переписанный (упрощенный) lock.go с одним интерфейсом KeyLock.

kl := NewKeyLock
kl.Block("key")
kl.Unblock("key")

и простенький тест, как сделать нормальный тест пока не понял.

2016-12-05 06:49 UTC, mtfelian requested changes
Backward compatibility should be retained

2016-12-05 06:49 UTC, mtfelian commented on lock.go
> -type lock struct {
Don't delete it, it is used in many packages

2016-12-05 06:49 UTC, mtfelian commented on lock_test.go
> +	// поэтому Sleep и никак иначе (есть другие варианты?)
Don't understand, how is it WG mutex interferes with local mutex?

2016-12-08 07:33 UTC, mtfelian commented on lock.go
> -	obj.once[key] = &sync.Once{}
Why no more Once here ?

2016-12-08 22:18 UTC, diaevd commented on lock.go
> -	obj.once[key] = &sync.Once{}
this no need anywere

2016-12-13 00:08 UTC, diaevd commented
Fix deadlock

2016-12-13 00:09 UTC, diaevd commented on lock_test.go
> +	// поэтому Sleep и никак иначе (есть другие варианты?)
This is was my bug, it realy did deadlock

2017-03-09 06:41 UTC, merged